(dp1
S'output'
p2
S'<class \'_mysql_exceptions.ProgrammingError\'> (1007, "Can\'t create database \'UserDB\'; database exists")'
p3
sS'layer'
p4
S'/home/adrian/web2py/applications/CygnusCloud/models/db.py'
p5
sS'code'
p6
S"# -*- coding: utf-8 -*-\nfrom configuration import DBConfigurator\n\n\nconf = DBConfigurator('170590ucm')\n#conf.dropDatabase('UserDB')\nconf.createDatabase('UserDB')\n#conf.addUser('CygnusCloud','cygnuscloud2012', 'UserDB')\nuserDB = DAL('mysql://CygnusCloud:cygnuscloud2012@localhost/UserDB',migrate_enabled=True)\n\n# Autentication\nfrom gluon.tools import Auth\nauth = Auth(userDB)\nauth.define_tables()\n      \nuserDB.define_table('ClassGroup',\n   Field('userId','integer', 'reference auth_user' ),\n   Field('cod','integer','reference UserGroup'),\n   Field('curseGroup','reference UserGroup',length=1 ),\n   primarykey=['cod','curseGroup','userId'],migrate= True)\n   \nuserDB.define_table('Subjects',\n   Field('code','integer'),\n   Field('name',length=15),migrate= True)\n   \nuserDB.define_table('UserGroup',\n   Field('yearGroup','integer', 'reference Users'),\n   Field('cod','integer','reference subjects'),\n   Field('curse','integer'),\n   Field('curseGroup', length=1),\n   primarykey=['cod','curseGroup'],migrate= True)\n   \nuserDB.define_table('VMByGroup',\n   Field('VMName',length=20),\n   Field('cod','integer','reference UserGroup'),\n   Field('curseGroup','reference UserGroup',length=1 ),\n   primarykey=['cod','curseGroup','VMName'],migrate= True)\n\n\n#Usuario de prueba\nu1 = userDB.auth_user.insert(password = userDB.auth_user.password.validate('1234')[0],\\\n                    email = 'Admin1@ucm.es',first_name='Bertoldo',last_name='Pedralbes')\n#A\xc3\xb1adimos los grupos\n#auth.add_group('Student', 'Only run virtual machines available')\n#auth.add_group('Administrator', 'All privilages available')\n\n#Enlazamos los usuarios a los grupos\n#auth.add_membership('Administrator',u1)\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/adrian/web2py/gluon/restricted.py", line 212, in restricted\n    exec ccode in environment\n  File "/home/adrian/web2py/applications/CygnusCloud/models/db.py", line 7, in <module>\n    conf.createDatabase(\'UserDB\')\n  File "applications/CygnusCloud/modules/configuration.py", line 51, in createDatabase\n    cursor.execute(command)\n  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute\n    self.errorhandler(self, exc, value)\n  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler\n    raise errorclass, errorvalue\nProgrammingError: (1007, "Can\'t create database \'UserDB\'; database exists")\n'
p11
s.