(dp1
S'output'
p2
S"<class '_mysql_exceptions.OperationalError'> (1075, 'Incorrect table definition; there can be only one auto column and it must be defined as a key')"
p3
sS'layer'
p4
S'/home/adrian/web2py/applications/CygnusCloud/models/db.py'
p5
sS'code'
p6
S"# -*- coding: utf-8 -*-\nfrom configuration import DBConfigurator\n\n\nconf = DBConfigurator('170590ucm')\nconf.createDatabase('userDB')\nuserDB = DAL('mysql://CygnusCloud:cygnuscloud2012@localhost/userDB')\n\n# Autentication\nfrom gluon.tools import Auth\nauth = Auth(userDB)\nauth.define_tables()\nauth.settings.table_user_name = 'Users'\nauth.settings.table_group_name = 'UserType'\nauth.settings.table_membership_name = 'TypeOf'\n\nuserDB.define_table('ClassGroup',\n   Field('userId','integer', 'reference Users' ),\n   Field('groupId','integer', 'reference Users'))\n   \nuserDB.define_table('Subjects',\n   Field('code','integer'),\n   Field('name',length=15))\n   \nuserDB.define_table('UserGroup',\n   Field('groupId', type='id'),\n   Field('yearGroup','integer', 'reference Users'),\n   Field('cod','integer','reference subjects'),\n   Field('curse','integer'),\n   Field('curseGroup', length=1),\n   primarykey=['cod','curseGroup'])\n   \nuserDB.define_table('VMByGroup',\n   Field('groupId','integer','reference UserGroup'),\n   Field('VMName',length=20))\n\n\nuserDB.UserGroup.groupId.writable = userDB.UserGroup.groupId.readable = False\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/adrian/web2py/gluon/restricted.py", line 212, in restricted\n    exec ccode in environment\n  File "/home/adrian/web2py/applications/CygnusCloud/models/db.py", line 31, in <module>\n    primarykey=[\'cod\',\'curseGroup\'])\n  File "/home/adrian/web2py/gluon/dal.py", line 7186, in define_table\n    table = self.lazy_define_table(tablename,*fields,**args)\n  File "/home/adrian/web2py/gluon/dal.py", line 7222, in lazy_define_table\n    polymodel=polymodel)\n  File "/home/adrian/web2py/gluon/dal.py", line 935, in create_table\n    self.create_sequence_and_triggers(query,table)\n  File "/home/adrian/web2py/gluon/dal.py", line 1694, in create_sequence_and_triggers\n    self.execute(query)\n  File "/home/adrian/web2py/gluon/dal.py", line 1709, in execute\n    return self.log_execute(*a, **b)\n  File "/home/adrian/web2py/gluon/dal.py", line 1703, in log_execute\n    ret = self.cursor.execute(*a, **b)\n  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute\n    self.errorhandler(self, exc, value)\n  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler\n    raise errorclass, errorvalue\nOperationalError: (1075, \'Incorrect table definition; there can be only one auto column and it must be defined as a key\')\n'
p11
s.